#!/bin/bash
if [ -e $1 ]
	then age=`stat -c %Y $1`

	shopt -s nullglob

	for file in *; do
		if [ `stat -c %Y $file` -gt "$age" ]
			then
				echo "$file"
		fi
	done
	else echo "$1 is not a valid file"
fi
